### ISSUE TITLE
Twitch shows always update from 8.2 to 8.3

### ISSUE THREAD

**Issue by StanoRiga** [Jaliborc/Combuctor_Broker#1]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.3.0

 **Have you read the changelog? (please don't waste our time)**
I did

**Describe the bug**
Every day the Twitch Client shows that I have 8.2 installed, and it wants to update to 8.3. Nevertheless I already have 8.3 installed, it does also not matter how often I run the update process. As soon as twich refreshes, the update is shown again (see screenshot).
I tried updating from twitch manually (download and copy files), I tried updateing with the github master version, no success.
The Version in Combuctor_Broker.toc says "## Version: 8.3.0"

**To Reproduce**
Steps to reproduce the behaviour:
Try to update from 8.2. via Twitch Client or any other way

**Expected behaviour**
As I have Version 8.3.0 installed, ther should be no update message

**Screenshots**
![com_broker](https://user-images.githubusercontent.com/30843029/77625007-112ee780-6f43-11ea-8e19-2205bab49781.png)

**Comment by Ph4d3** [comment]
I also have this issue.

**Comment by StanoRiga** [comment]
3 month without a reply.
Looks abandoned to me.
We're gonna have to look for another bag solution for Shadowlands.

**Comment by Ph4d3** [comment]
I also still have this issue. it continually shows up as needing to update.

**Comment by Ph4d3** [comment]
> I also still have this issue. it continually shows up as needing to update.

This is now fixed thanks!
